/*
 * cyberspace is 3D first person mmorpg game engine, with 2D minigame
 * plugins, initially developed to be used on LAN as an additional
 * game element for a cyberpunk LARPG.
 *
 * Copyright (C) 2008-2012 Claudio Felicioli
 * mail: pangon@gmail.com
 *
 * cyberspace is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */


#ifndef CYBERSPACE_CONSTANTS
#define CYBERSPACE_CONSTANTS

#define CYBERSPACE_SERVER_VERSION_MAJOR 0
#define CYBERSPACE_SERVER_VERSION_MINOR 1

#define CYBERSPACE_CONNECTOR_MODEL_CRAP 0

#define CYBERSPACE_PHASE_CONNECTING 0
#define CYBERSPACE_PHASE_LOGIN 1
#define CYBERSPACE_PHASE_3D 2
#define CYBERSPACE_PHASE_PROGRAMMING 3
#define CYBERSPACE_PHASE_MINIGAME_TESTING 4
#define CYBERSPACE_PHASE_MINIGAME_HEURISTIC 5
#define CYBERSPACE_PHASE_MINIGAME_FAST 6
#define CYBERSPACE_PHASE_MINIGAME_PATTERNMATCHING 7

#define CYBERSPACE_PHASE_PROGRAMMING_SYS 0
#define CYBERSPACE_PHASE_PROGRAMMING_SUBSYS 1
#define CYBERSPACE_PHASE_PROGRAMMING_DEVELOP 2
#define CYBERSPACE_PHASE_PROGRAMMING_STEPS 3

#define CYBERSPACE_COMMAND_USER_LOGIN 0
#define CYBERSPACE_COMMAND_USER_MOVEMENT 1
#define CYBERSPACE_COMMAND_USER_ACTION 2
#define CYBERSPACE_COMMAND_USER_CHAT 3
#define CYBERSPACE_COMMAND_USER_SKILL_0 4
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_STOP 5
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_SYSTEM_LOAD 6
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_SYSTEM_UNLOAD 7
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_CODE 8
#define CYBERSPACE_COMMAND_USER_MINIGAME_TESTING_DONE 9
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_TRAINING_HEURISTIC 10
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_TRAINING_FAST 11
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_TRAINING_PATTERNMATCHING 12
#define CYBERSPACE_COMMAND_USER_MINIGAME_HEURISTIC_DROP 13
#define CYBERSPACE_COMMAND_USER_MINIGAME_FAST_DONE 14
#define CYBERSPACE_COMMAND_USER_MINIGAME_PATTERNMATCHING_DONE 15
#define CYBERSPACE_COMMAND_USER_LOGOUT 16
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_HEURISTIC 17
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_FAST 18
#define CYBERSPACE_COMMAND_USER_PROGRAMMING_PATTERNMATCHING 19

#define CYBERSPACE_COMMAND_SERVER_ERROR 0
#define CYBERSPACE_COMMAND_SERVER_PHASE_LOGIN 1
#define CYBERSPACE_COMMAND_SERVER_PHASE_3D 2
#define CYBERSPACE_COMMAND_SERVER_WORLD_LOAD 3
#define CYBERSPACE_COMMAND_SERVER_WORLD_SYNC 4
#define CYBERSPACE_COMMAND_SERVER_USER 5
#define CYBERSPACE_COMMAND_SERVER_CHAT 6
#define CYBERSPACE_COMMAND_SERVER_PHASE_PROGRAMMING 7
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_TESTING 8
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_TESTING_POINTS 9
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_HEURISTIC 10
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_HEURISTIC_PIECE 11
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_FAST 12
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_FAST_POINTS_AND_MAP 13
#define CYBERSPACE_COMMAND_SERVER_PHASE_MINIGAME_PATTERNMATCHING 14
#define CYBERSPACE_COMMAND_SERVER_PROGRAMMING 15

#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_PROGRAMMING 0
#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_TRAINING_HEURISTIC 1
#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_TRAINING_FAST 2
#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_TRAINING_PATTERNMATCHING 3
//#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_HEURISTIC 4
//#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_FAST 5
//#define CYBERSPACE_COMMAND_MINIGAME_CAUSE_PATTERNMATCHING 6

#define CYBERSPACE_MINIGAME_HEURISTIC_MAP_W 8
#define CYBERSPACE_MINIGAME_HEURISTIC_MAP_H 6

#define CYBERSPACE_MINIGAME_FAST_MAP_L 12
#define CYBERSPACE_MINIGAME_FAST_PATH_LENGTH 6
#define CYBERSPACE_MINIGAME_FAST_MAXREROLLS 20
#define CYBERSPACE_MINIGAME_FAST_MAP_FLOOR 0
#define CYBERSPACE_MINIGAME_FAST_MAP_RADIO 1
#define CYBERSPACE_MINIGAME_FAST_MAP_CAN 2
#define CYBERSPACE_MINIGAME_FAST_MAP_END 3
#define CYBERSPACE_MINIGAME_FAST_MAP_START 4
#define CYBERSPACE_MINIGAME_FAST_MAP_CRYSTAL 5
#define CYBERSPACE_MINIGAME_FAST_MAP_CRYSTAL_GET 6

#define CYBERSPACE_FRONTDOOR_SOCKET_PORT_C2S 10666
#define CYBERSPACE_FRONTDOOR_SOCKET_PORT_STRING_C2S "10666"
#define CYBERSPACE_FRONTDOOR_SOCKET_PORT_S2C 10667
#define CYBERSPACE_FRONTDOOR_SOCKET_PORT_STRING_S2C "10667"
#define CYBERSPACE_USER_CONNECTION_READ_BUFFER 100000
#define CYBERSPACE_USER_CONNECTION_WRITE_BUFFER 100000
#define CYBERSPACE_STATISTICS_FREQUENCY 5
#define CYBERSPACE_CONNECTIONS_MAX 100

#define CYBERSPACE_COMMAND_SIZE_S 100
#define CYBERSPACE_COMMAND_SIZE_M 1000
#define CYBERSPACE_COMMAND_SIZE_L 10000

//#define CYBERSPACE_GUI_WIDTH 400
//#define CYBERSPACE_GUI_HEIGHT 400
//#define CYBERSPACE_GUI_WIDTH 800
//#define CYBERSPACE_GUI_HEIGHT 480
#define CYBERSPACE_GUI_WIDTH 1024
#define CYBERSPACE_GUI_HEIGHT 768

#define CYBERSPACE_GUI_UNSET 0
#define CYBERSPACE_GUI_SDL 1
#define CYBERSPACE_GUI_GL 2

#define CYBERSPACE_GUI_WIREFRAMES false

#define CYBERSPACE_GUI_TESSELLATION_SIZE_WALL 50.0
#define CYBERSPACE_GUI_TESSELLATION_SIZE_WALL_WIRE 100.0
#define CYBERSPACE_GUI_TESSELLATION_SIZE_FLOOR 100.0

#define CYBERSPACE_WORLD_STATIC_OBJECTS_MAX 100
#define CYBERSPACE_WORLD_DYNAMIC_OBJECTS_MAX 1000
#define CYBERSPACE_WORLD_RED_LINES_MAX 1000
#define CYBERSPACE_WORLD_FLOORS_MAX 1000

#define CYBERSPACE_WORLD_MAP_SCALE 100.0

#define CYBERSPACE_WORLD_OBJECT_CUBE 0
#define CYBERSPACE_WORLD_OBJECT_USER 1
#define CYBERSPACE_WORLD_OBJECT_REDLINE 2
#define CYBERSPACE_WORLD_OBJECT_VECTOR 3
#define CYBERSPACE_WORLD_OBJECT_TELEPORT_INTERWORLD 4
#define CYBERSPACE_WORLD_OBJECT_WALL 5
#define CYBERSPACE_WORLD_OBJECT_FLOOR 6
#define CYBERSPACE_WORLD_OBJECT_CONSOLE 7
#define CYBERSPACE_WORLD_OBJECT_NONE 8

#define CYBERSPACE_WORLD_OBJECT_PARAMETERS_MAX 6

#define CYBERSPACE_WORLD_OBJECT_USER_R 10.0
#define CYBERSPACE_WORLD_OBJECT_USER_H 50.0
#define CYBERSPACE_WORLD_OBJECT_USER_PARAMETER_ID_STATIC 0
#define CYBERSPACE_WORLD_OBJECT_USER_PARAMETER_ID_DYNAMIC 1

#define CYBERSPACE_WORLD_OBJECT_REDLINE_PARAMETER_LENGTH 0

#define CYBERSPACE_WORLD_OBJECT_VECTOR_PARAMETER_LENGTH 0

#define CYBERSPACE_WORLD_OBJECT_TELEPORT_INTERWORLD_PARAMETER_TARGET_WORLD 0
#define CYBERSPACE_WORLD_OBJECT_TELEPORT_INTERWORLD_PARAMETER_TARGET_X 1
#define CYBERSPACE_WORLD_OBJECT_TELEPORT_INTERWORLD_PARAMETER_TARGET_Y 2
#define CYBERSPACE_WORLD_OBJECT_TELEPORT_INTERWORLD_PARAMETER_TARGET_Z 3
#define CYBERSPACE_WORLD_OBJECT_TELEPORT_INTERWORLD_PARAMETER_SKIN 4

#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_HEIGHT 0
#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_LENGTH 1
#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_SUBTYPE 2

#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_SUBTYPE_STEEL 0
#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_SUBTYPE_GLASS_STEEL 1
#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_SUBTYPE_WIRE 2
#define CYBERSPACE_WORLD_OBJECT_WALL_PARAMETER_SUBTYPE_FORCEFIELD 3

#define CYBERSPACE_WORLD_OBJECT_FLOOR_PARAMETER_X0 0
#define CYBERSPACE_WORLD_OBJECT_FLOOR_PARAMETER_Z0 1
#define CYBERSPACE_WORLD_OBJECT_FLOOR_PARAMETER_X1 2
#define CYBERSPACE_WORLD_OBJECT_FLOOR_PARAMETER_Z1 3
#define CYBERSPACE_WORLD_OBJECT_FLOOR_PARAMETER_X2 4
#define CYBERSPACE_WORLD_OBJECT_FLOOR_PARAMETER_Z2 5


#define CYBERSPACE_WORLD_GRAVITY 0.1

#define CYBERSPACE_DEBUG_GUI_MODE false

#define CYBERSPACE_GUI_CHAT_HISTORY 13
#define CYBERSPACE_GUI_CHAT_LINE_WIDTH 60

#define CYBERSPACE_GUI_INPUT_FOCUS_NONE 0
#define CYBERSPACE_GUI_INPUT_FOCUS_LOGIN 1
#define CYBERSPACE_GUI_INPUT_FOCUS_PASSWORD 2
#define CYBERSPACE_GUI_INPUT_FOCUS_CHAT 3

#define CYBERSPACE_GUI_FRAME_FREQUENCY 50

#define CYBERSPACE_NEURAL_SYSTEM_MOVEMENT 0
#define CYBERSPACE_NEURAL_SYSTEM_SCAN 1
#define CYBERSPACE_NEURAL_SYSTEM_OBFUSCATION 2
#define CYBERSPACE_NEURAL_SYSTEM_ATTACK 3
#define CYBERSPACE_NEURAL_SYSTEM_DEFENCE 4

#define CYBERSPACE_NEURAL_SYSTEM_MAX 5

#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_SPEED 0
#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_JUMP 1

#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_MAP 0
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_SCAN 1
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_COOR 2

#define CYBERSPACE_NEURAL_SUBSYSTEM_ATTACK_TOUCH 0

#define CYBERSPACE_NEURAL_SUBSYSTEM_DEFENCE_TOUCH 0

#define CYBERSPACE_NEURAL_SUBSYSTEM_MAX 10

#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_SPEED_I_HEUR 3000
#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_SPEED_I_FAST 75
#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_SPEED_I_PATTERN 0

#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_JUMP_I_HEUR 5000
#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_JUMP_I_FAST 100
#define CYBERSPACE_NEURAL_SUBSYSTEM_MOVEMENT_JUMP_I_PATTERN 0

#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_MAP_I_HEUR 0
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_MAP_I_FAST 0
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_MAP_I_PATTERN 100

#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_SCAN_I_HEUR 10000
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_SCAN_I_FAST 100
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_SCAN_I_PATTERN 100

#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_COOR_I_HEUR 2000
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_COOR_I_FAST 50
#define CYBERSPACE_NEURAL_SUBSYSTEM_SCAN_COOR_I_PATTERN 100

#define CYBERSPACE_NEURAL_SUBSYSTEM_ATTACK_TOUCH_I_HEUR 10000
#define CYBERSPACE_NEURAL_SUBSYSTEM_ATTACK_TOUCH_I_FAST 75
#define CYBERSPACE_NEURAL_SUBSYSTEM_ATTACK_TOUCH_I_PATTERN 0

#define CYBERSPACE_NEURAL_SUBSYSTEM_DEFENCE_TOUCH_I_HEUR 10000
#define CYBERSPACE_NEURAL_SUBSYSTEM_DEFENCE_TOUCH_I_FAST 100
#define CYBERSPACE_NEURAL_SUBSYSTEM_DEFENCE_TOUCH_I_PATTERN 0

#define CYBERSPACE_GUI_TEXTURE_TILE_32_CAN 0
#define CYBERSPACE_GUI_TEXTURE_TILE_32_RADIO 1
#define CYBERSPACE_GUI_TEXTURE_TILE_32_CRYSTAL 2
#define CYBERSPACE_GUI_TEXTURE_TILE_32_START 3
#define CYBERSPACE_GUI_TEXTURE_TILE_32_END 4
#define CYBERSPACE_GUI_TEXTURE_TILE_32_FLOOR 5
#define CYBERSPACE_GUI_TEXTURE_TILE_32_CULT_0 6
//#define CYBERSPACE_GUI_TEXTURE_TILE_256_SELF 7
#define CYBERSPACE_GUI_TEXTURE_TILES_4X4_64_ICONS 7

#define CYBERSPACE_GUI_TEXTURES_MAX 10

#define CYBERSPACE_SERVER_NAME "127.0.0.1"
//#define CYBERSPACE_SERVER_NAME "192.168.1.37"
//#define CYBERSPACE_SERVER_NAME "192.168.1.6"
//#define CYBERSPACE_SERVER_NAME "192.168.1.9"

#define CYBERSPACE_LOGOUT_MILLISECONDS 5000

#endif /* CYBERSPACE_CONSTANTS */
